#!/usr/bin/env ansible-playbook
---
- name: Configure webserver with nginx
  hosts: localhost
  become: True
  vars:
          - key: "/etc/ssl/private/server.key"
          - cert: "/etc/ssl/certs/server.crt"
          - dh: "/etc/ssl/certs/dhparam.pem"  

  tasks:
          - name: install nginx
            apt: name=nginx state=latest update_cache=yes

          - name: create self-signed certificate and priv key 
            command: >
                    openssl req -x509 -nodes -subj '/CN=localhost' -days 365
                    -newkey rsa:4096 -sha256 -keyout {{ key }} -out {{ cert }}
                    creates={{ cert }}
        
          - name: create dh 
            command: openssl dhparam -out {{dh}} 2048
                     creates={{dh}}
        
          - name: copy nginx config file
            copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf
          
          - name: copy nginx default file
            copy: src=files/default dest=/etc/nginx/sites-available/default

          - name: copy index.html
            template: src=templates/index.html.j2 dest=/var/www/html/index.html mode=0644
          
          - name: copy snippets
            template: src=templates/{{item}} dest=/etc/nginx/snippets/{{item}} mode=0644
            with_items:
                    - self-signed.conf 
                    - ssl-params.conf  

          - name: restart nginx
            service: name=nginx state=restarted


- name: Include playbook docker_up
  import_playbook: docker_up.yml



